### ISSUE TITLE
ADD algorithms from ADS and AoC solutions to the repository

### ISSUE THREAD

**Issue by vlad-nitu** [vlad-nitu/ads#1]
# TO-DOs
- [x] Have relevant algorithms merged on 'master' branch
- [x] Add simple QS and HeapSort when available on WebLab
- [x] Have AdventOfCode solutions merged on 'master' branch
